import embedded.mas.bridges.ros.Ros4EmbeddedMas;
import embedded.mas.bridges.jacamo.IPhysicalInterface;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package serial_read;

//import embedded.mas.bridges.javard.Arduino4EmbeddedMas;
//import embedded.mas.bridges.jacamo.IPhysicalInterface;

public class serial_read {

    /*public static void main(String[] args) {
        IPhysicalInterface a = new Ros4EmbeddedMas(); //Ros4EmbeddedMas can be replaced by any IPhysicalInterface to be tested
        String s = a.read(); //read from serial until getting a linebreak (\n)
        System.out.println(s);
    }*/

    public static void main(String[] args) {

        IPhysicalInterface a = new Ros4EmbeddedMas(); //Ros4EmbeddedMas can be replaced by any IPhysicalInterface to be tested

        String s = a.read(); //read from serial until getting a linebreak (\n)

        //a.write("init");

        while(true){
            try {
                s = a.read();
                if (s != null){
                    System.out.println("s: "+s);
                }
            }catch (Exception e){
                System.out.println("erro");
            }
		}
    }
}
